version: '3.9'

services:
  web:
    build: .
    container_name: web_barber_shop
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    depends_on:
      - db    
  db:
    image: postgres:16.0-bullseye
    container_name: db_barber_shop
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:    

